name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: google-github-actions/release-please-action@v3.7.8
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          include-v-in-tag: false
          bump-minor-pre-major: true
          extra-files: |
            README.md
