name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: google-github-actions/release-please-action@v4.1.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          include-v-in-tag: false
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          extra-files: |
            README.md
